### ISSUE TITLE
Enable multiple-language portal support : Script Error

### ISSUE THREAD

**Issue by clement-vs-invest** [MicrosoftDocs/powerapps-docs.fr-fr#10]
I want to enable multi-language  on my portals but when I want to  add new langages  to the portal, I  have a script error and I don't understand why

One of the scripts for this record has caused an error. For more details, download the log file.
Web resource method does not exist: adx.multilanguage.website.onWebsiteLanguageLoad
Session Id: 
Correlation Id: 
Time: Thu Jun 18 2020 12:22:29 GMT+0200 (heure d’été d’Europe centrale).

**Comment by srvbpigh** [comment]
Bonjour @clement-vs-invest,

Nous développons notre pipeline de processus interne et d’ingénierie. Malheureusement, cela se traduit par des retards dans le traitement de vos commentaires.

Nous apprécions beaucoup votre contribution à nos articles et comptons sur votre aide et votre compréhension.
