### ISSUE TITLE
Excellent !

### ISSUE THREAD

**Issue by wanajo38** [MicrosoftDocs/powerapps-docs.fr-fr#3]
Bravo car la documentation pour PowerApps est vraiment riche, en plus en français. C'est vraiment parfait ! C'est compliqué mais grâce à toute cette documentation de qualité on finit par y arriver. J'ai rarement vu autant de documentation (surtout en français) pour une application. C'est très bien construit et plutôt intuitif, merci beaucoup !

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 59975a54-2a0b-0148-0fd1-a4ffd51c8d5a
* Version Independent ID: d3faf9fc-d312-db0b-1369-d72c3bd47fd3
* Content: [Fonctions, signaux et énumérations - PowerApps](https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/formula-reference)
* Content Source: [powerapps-docs/maker/canvas-apps/formula-reference.md](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/blob/live/powerapps-docs/maker/canvas-apps/formula-reference.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by LisandroSu** [comment]
Bonjour @wanajo38 

Merci pour votre feedback. Nous sommes heureux d’apprendre que notre documentation répond à vos attentes. 
Dans une optique d’amélioration constante, nous vous encourageons à envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
