### ISSUE TITLE
Audio Format from PowerApps Desktop

### ISSUE THREAD

**Issue by allandecastro** [MicrosoftDocs/powerapps-docs.fr-fr#6]
Hello,
For information, using the PowerApps application on a PC ( on Microsoft Store), audio files are in .m4a format (ex: ms-appdata:///local/recording_abcce391-c00c-49d5-9b71-cf4c328c7dd1.m4a)

Regards,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 258f140b-bc82-47a7-e915-79bebbd9b3b9
* Version Independent ID: d8a732b6-53b4-b161-3ff8-14de5fda89b3
* Content: [Contrôle Microphone : référence - PowerApps](https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/controls/control-microphone#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/controls/control-microphone.md](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/blob/live/powerapps-docs/maker/canvas-apps/controls/control-microphone.md)
* Service: **powerapps**
* GitHub Login: @fikaradz
* Microsoft Alias: **fikaradz**

**Comment by CeciAc** [comment]
Hello, @allandecastro 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @allandecastro
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @allandecastro 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
