### ISSUE TITLE
Launch function Syntax

### ISSUE THREAD

**Issue by QVERNILLAT** [MicrosoftDocs/powerapps-docs.fr-fr#7]
The syntax of the launch function is : Launch("Address")

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: edbd7c88-66b5-0776-251e-49293324b930
* Version Independent ID: 4364fe0e-c13d-afaa-a0b3-1e5803e1d9e8
* Content: [Fonctions Download, Launch et Param - PowerApps](https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/functions/function-param#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-param.md](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/blob/live/powerapps-docs/maker/canvas-apps/functions/function-param.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by CeciAc** [comment]
Hello, @QVERNILLAT
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @QVERNILLAT
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
