### ISSUE TITLE
Markdown for Control property is not rendered correctly (French version)

### ISSUE THREAD

**Issue by MscrmTools** [MicrosoftDocs/powerapps-docs.fr-fr#8]
Markdown for Control property is not rendered correctly. There must be a typo somewhere

Here is the url: https://docs.microsoft.com/fr-fr/powerapps/developer/component-framework/manifest-schema-reference/control

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 81dbe6f9-23c2-d7db-4de5-e23f7d101568
* Version Independent ID: 9cd7461d-dc9d-4825-1bc9-1b9fa059c967
* Content: [Control, élément - Power Apps](https://docs.microsoft.com/fr-fr/powerapps/developer/component-framework/manifest-schema-reference/control)
* Content Source: [powerapps-docs/developer/component-framework/manifest-schema-reference/control.md](https://github.com/MicrosoftDocs/powerapps-docs.fr-fr/blob/live/powerapps-docs/developer/component-framework/manifest-schema-reference/control.md)
* Service: **powerapps**
* GitHub Login: @Nkrb
* Microsoft Alias: **nabuthuk**

**Comment by srvbpigh** [comment]
Hello, @MscrmTools
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by jowilco** [comment]
The broken tagging is now fixed.
